name: nike_shoes_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  ionicons: ^0.2.2
  iconly: ^1.0.1
  equatable: ^2.0.5
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  flutter_localizations:
    sdk: flutter
  smooth_page_indicator: ^1.2.0+3
  expand_widget: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar-Regular.ttf
    - family: Estedad-Medium
      fonts:
        - asset: assets/fonts/Estedad-Medium.ttf
    - family: Estedad-Regular
      fonts:
        - asset: assets/fonts/Estedad-Regular.ttf